oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

moueza_core:
    resource: "@mouezaCoreBundle/Resources/config/routing.yml"
    prefix:   /core

app:
    resource: '@AppBundle/Controller/'
    type: annotation
