#OC platform config
oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Default:index }





oc_platform_home:
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index2
        page:        1
    requirements:
        page: \d*
    
oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view2
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+




oc_platform_view_slugZF:
    path:      /{year}/{slug}.{format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
    requirements:
        year: \d+
        slug: "a"
        format: "zf"

oc_platform_view_slugF:
    path:      /{year}/{slug}.{format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
    requirements:
        year: \d+
        slug: "[a-z]"
        format: "f"
oc_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
    requirements:
        year: \d+
        slug: "[a-zA-Z]+"
        format: "[a-z]+"
